apiVersion: v1
kind: BuildConfig
metadata:
  name: dropwizard-example-pipeline
spec:
  source:
    git:
      uri: "https://github.com/gourp/dropwizard-example"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile